import Foundation

enum MovieDescriptions {
    static let descriptions: [String: String] = [
        // Movies
        "gravity": "A medical engineer and an astronaut work together to survive after debris destroys their shuttle, leaving them stranded in orbit.",
        "midnight express": "An American college student is arrested for drug smuggling in Turkey and faces a brutal, dehumanizing prison system.",
        "12 strong": "The first U.S. Special Forces team deployed to Afghanistan after 9/11 must partner with a Northern Alliance warlord to take down the Taliban.",
        "1917": "Two young British soldiers race against time across enemy territory to deliver a message that could save 1,600 men from walking into a deadly trap.",
        "a haunted house": "A young couple moves into a new home only to discover it's haunted, leading to increasingly absurd paranormal encounters.",
        "a knights tale": "A peasant squire with dreams of knighthood assumes a dead knight's identity to compete in jousting tournaments across medieval Europe.",
        "a man called otto": "A grumpy widower who's given up on life finds his world turned upside down when a lively young family moves in next door.",
        "abraham lincoln vampire hunter": "The 16th President of the United States discovers vampires are planning to take over the nation, and he sets out to eliminate them with an axe.",
        "act of valor": "An elite team of Navy SEALs embarks on a covert mission to rescue a kidnapped CIA operative and uncovers a terrorist plot threatening the U.S.",
        "all the pretty horses": "A young Texan and his best friend ride horseback into Mexico seeking the cowboy life, but romance and a wrongful arrest derail their journey.",
        "all the money in the world": "When teenage John Paul Getty III is kidnapped in Rome, his billionaire grandfather refuses to pay the ransom, forcing his mother to fight for his life.",
        "american hustle": "A brilliant con artist and his partner are forced by an ambitious FBI agent to set up an elaborate sting operation targeting corrupt politicians.",
        "american reunion": "The gang from East Great Falls reunites for their high school reunion, proving that some things never change no matter how old you get.",
        "apocalypto": "A young Mayan man captured for human sacrifice must fight to escape and return to his pregnant wife before it's too late.",
        "appaloosa": "Two itinerant lawmen arrive in a small frontier town to bring order, but a beautiful widow threatens to come between them.",
        "arctic": "A man stranded in the Arctic after a plane crash must decide whether to remain in the relative safety of his camp or embark on a deadly trek to find rescue.",
        "argo": "A CIA operative hatches an audacious plan to rescue six American hostages from Tehran by disguising them as a Canadian film crew scouting locations.",
        "avengers": "Earth's mightiest heroes are forced to band together to stop Loki and his alien army from enslaving humanity.",
        "baby makers": "A couple desperate to have a baby hatch a scheme to rob a sperm bank after discovering the husband is infertile.",
        "bashir": "An Israeli filmmaker interviews fellow veterans of the 1982 Lebanon War using animation to reconstruct memories they've long suppressed.",
        "battleship": "A fleet of warships encounters an alien armada during naval exercises and must fight to prevent an extraterrestrial invasion.",
        "bernie": "A beloved small-town mortician in East Texas befriends a wealthy widow, but their unlikely relationship takes a dark and deadly turn.",
        "blade runner 2049": "A young blade runner uncovers a long-buried secret that has the potential to plunge what's left of society into chaos, leading him on a quest to find a missing former blade runner.",
        "body of lies": "A CIA operative on the ground in the Middle East navigates a web of deception to infiltrate a terrorist network, while his handler plays a different game from Washington.",
        "bridge of spies": "During the Cold War, a Brooklyn lawyer is recruited to negotiate the release of a captured American U-2 pilot in exchange for a convicted Soviet spy.",
        "broken city": "An ex-cop turned private investigator is hired by New York's mayor to tail his wife, only to uncover a massive conspiracy that threatens to destroy them both.",
        "bullitt": "A San Francisco detective assigned to protect a mob witness investigates a double-cross, leading to one of cinema's most legendary car chases.",
        "cartel land": "Vigilante groups on both sides of the U.S.-Mexico border take up arms against the drug cartels that have terrorized their communities.",
        "casino royale": "In his first mission as 007, James Bond must defeat a weapons dealer in a high-stakes poker game at Casino Royale to prevent him from funding terrorism.",
        "catch a fire": "A South African oil refinery foreman is radicalized into joining the anti-apartheid resistance after being wrongfully detained and tortured by the security police.",
        "cheech and chong up in smoke": "Two perpetually stoned friends unknowingly smuggle a van made entirely of marijuana from Mexico to Los Angeles.",
        "children of men": "In a bleak future where humanity has become infertile, a disillusioned bureaucrat must escort a miraculously pregnant woman to safety.",
        "cloverfield": "A group of friends document their terrifying escape through the streets of Manhattan as a massive creature attacks New York City.",
        "cocaine cowboys": "The true story of how Miami became the drug capital of the United States in the 1970s and '80s through the eyes of smugglers and law enforcement.",
        "collateral": "A contract killer hijacks a cab driver's taxi for a night of assassinations across Los Angeles, and the driver must find a way to survive.",
        "contraband": "A former smuggler is pulled back into the underworld to settle his brother-in-law's debt by running counterfeit currency from Panama to New Orleans.",
        "cool hand luke": "A defiant prisoner in a Southern chain gang refuses to submit to the system, earning the admiration of his fellow inmates and the wrath of his captors.",
        "cowboys and aliens": "A stranger with no memory of his past stumbles into a frontier town just as alien invaders attack, forcing outlaws and locals to unite against the threat.",
        "cry macho": "A washed-up rodeo star is hired to bring a man's young son back from Mexico, and the journey becomes a path to redemption for both of them.",
        "cut bank": "When a young man accidentally films what appears to be a murder in a small Montana town, his attempt to collect the reward money spirals into something far more dangerous.",
        "dallas buyers club": "An electrician diagnosed with AIDS in 1985 defies the medical establishment by smuggling unapproved pharmaceuticals into Texas to treat himself and others.",
        "dark knight rises": "Eight years after the Joker's reign of terror, Batman must return to protect Gotham from a ruthless mercenary who plans to fulfill Ra's al Ghul's destiny.",
        "dark shadows": "A centuries-old vampire is freed from his grave and returns to his crumbling family estate, struggling to adapt to the strange world of the 1970s.",
        "darkest hour": "Winston Churchill faces his most turbulent days as newly appointed Prime Minister, navigating political rivals and the looming threat of Nazi invasion.",
        "deadpool": "A wisecracking mercenary with accelerated healing powers hunts down the man who nearly destroyed his life and left him horribly disfigured.",
        "death proof": "A sadistic stuntman uses his death-proof car to murder young women on the road, until he picks the wrong group of targets.",
        "dien bien phu": "The story of the decisive 1954 battle between French colonial forces and Viet Minh fighters that ended France's involvement in Indochina.",
        "district 9": "When extraterrestrial refugees are confined to a slum in Johannesburg, a government agent exposed to their technology begins a shocking transformation.",
        "django unchained": "A freed slave teams up with a German bounty hunter to rescue his wife from a brutal Mississippi plantation owner.",
        "dredd": "In a dystopian mega-city, a no-nonsense judge and his rookie partner are locked inside a 200-story tower block controlled by a ruthless drug lord.",
        "dune": "The son of a noble family is thrust into a war for control of the galaxy's most valuable resource on the most dangerous planet in the universe.",
        "edge of tomorrow": "A soldier caught in a time loop during an alien invasion relives the same brutal battle over and over, getting better with each reset.",
        "elysium": "In a future where the wealthy live on a luxurious space station and the poor are stuck on a ruined Earth, a desperate man fights to bring equality to both worlds.",
        "empire of the sun": "A privileged British boy is separated from his parents during the Japanese invasion of Shanghai and must survive in an internment camp.",
        "end of watch": "Two young LAPD officers patrolling South Central Los Angeles form an unbreakable bond as they unknowingly cross a powerful drug cartel.",
        "equilibrium": "In a dystopian future where emotions are outlawed, an elite law enforcement officer begins to question the system after he stops taking his mandatory medication.",
        "fantastic fungi": "A visually stunning documentary exploring the mysterious and medicinal world of fungi and their power to heal, sustain, and contribute to life on Earth.",
        "felon": "A family man sent to prison for killing an intruder must navigate a brutal yard ruled by gangs and corrupt guards to survive.",
        "fifth element": "In a colorful 23rd-century future, a cab driver and a mysterious woman must recover four mystical stones to save the world from an ancient evil.",
        "finch": "A dying robotics engineer builds an android to care for his beloved dog after he's gone, and the three embark on a journey across a post-apocalyptic American West.",
        "flight": "An airline pilot miraculously crash-lands his plane after a mechanical failure, but the investigation reveals he was intoxicated during the flight.",
        "ford v ferrari": "Car designer Carroll Shelby and driver Ken Miles battle corporate interference to build a revolutionary race car for Ford and challenge Ferrari at Le Mans in 1966.",
        "free state of jones": "A defiant Mississippi farmer leads a ragtag group of rebels against the Confederacy during the Civil War, establishing a free state in the heart of the South.",
        "fury": "In the final days of World War II, a battle-hardened tank commander and his crew fight their way across Germany on a deadly mission behind enemy lines.",
        "get the gringo": "An American criminal is thrown into a tough Mexican prison and must use his wits to survive while plotting an escape with the help of a young boy.",
        "glengarry glen ross": "Desperate real estate salesmen will do anything to close deals and save their jobs when the home office announces that all but the top two sellers will be fired.",
        "gran torino": "A racist Korean War veteran forms an unlikely bond with his Hmong neighbors and must confront the local gang terrorizing their community.",
        "haven": "On a Caribbean island, multiple storylines intertwine as characters deal with forbidden romance, drug smuggling, and violent retribution.",
        "here comes the boom": "A bored biology teacher takes up mixed martial arts fighting to raise enough money to save his school's music program.",
        "hero": "A nameless warrior tells the King of Qin how he defeated three legendary assassins, but each version of the story reveals a deeper truth.",
        "home": "When misfit alien Oh accidentally sends a party invitation to the entire galaxy, he goes on the run with a resourceful human girl to fix his mistake.",
        "hotel mumbai": "The true story of the staff and guests at the Taj Mahal Palace Hotel who fought to survive during the devastating 2008 terrorist attacks in Mumbai.",
        "house at the end of the street": "A mother and daughter move to a new town and discover that their neighbor's house was the site of a double murder, with the surviving son still living there.",
        "hyena road": "Three different perspectives converge in this story of Canadian soldiers, a sniper team, and an enigmatic Afghan elder during the war in Afghanistan.",
        "i am legend": "The last human survivor in New York City struggles to find a cure for a man-made plague that has turned the rest of humanity into bloodthirsty mutants.",
        "immortals": "A stonemason is chosen by Zeus to lead the fight against a ruthless king who is on a warpath to unleash the imprisoned Titans upon the world.",
        "in the valley of elah": "A retired military investigator searches for his son who has gone missing after returning from a tour in Iraq, uncovering a disturbing truth.",
        "incredible burt wonderstone": "A famous Las Vegas magician whose act has grown stale faces off against an edgy new street performer who threatens to steal his audience.",
        "inglourious basterds": "A squad of Jewish-American soldiers plots to assassinate Nazi leaders in occupied France, while a cinema owner plans her own deadly revenge.",
        "jack reacher": "A former military investigator surfaces to take on a case involving a trained sniper accused of a seemingly random shooting spree in Pittsburgh.",
        "jack reacher never go back": "Jack Reacher returns to his old military headquarters only to find his replacement arrested for treason, pulling him into a conspiracy that runs deep.",
        "jimi hendrix": "The story of legendary guitarist Jimi Hendrix's rise from a struggling musician to the most celebrated rock performer of his era.",
        "joe's palace": "A shy young man working as a caretaker in a wealthy man's empty London townhouse discovers secrets about its owner's past and the hidden history within its walls.",
        "john carter": "A Civil War veteran is mysteriously transported to Mars, where he becomes reluctantly embroiled in a conflict between the planet's warring nations.",
        "john dies at the end": "Two college dropouts encounter a bizarre street drug called Soy Sauce that sends users across time and dimensions, and they become humanity's unlikely saviors.",
        "john wick": "A retired hitman is pulled back into the criminal underworld when a gangster's son steals his car and kills the puppy that was his last gift from his wife.",
        "john wick chapter 2": "Legendary hitman John Wick is forced out of retirement again by a former associate who calls in a blood oath, sending him on a globe-trotting mission of vengeance.",
        "journey 2": "A teenager and his stepfather travel to a remote island in the Pacific to find the boy's missing grandfather, discovering a land of mythical creatures.",
        "jurassic world": "Twenty-two years after the original Jurassic Park disaster, a fully operational dinosaur theme park on the same island faces a new crisis when a genetically modified hybrid escapes.",
        "kill bill vol 1": "A former assassin awakens from a coma and sets out on a bloody quest for revenge against the team of killers who betrayed her on her wedding day.",
        "killer joe": "A drug dealer hires a corrupt detective to kill his mother for the insurance money, but the detective's price comes with twisted strings attached.",
        "killers of the flower moon": "In 1920s Oklahoma, members of the Osage Nation are murdered one by one after oil is discovered on their land, sparking one of the FBI's first major investigations.",
        "killing them softly": "A professional enforcer investigates a heist that went down during a mob-protected poker game, methodically restoring order in the criminal underworld.",
        "kiss of the damned": "A beautiful vampire tries to resist the advances of a screenwriter, but their forbidden love is threatened by her dangerously unhinged sister.",
        "knives out": "When a renowned crime novelist is found dead after his 85th birthday party, a suave detective investigates his dysfunctional family to uncover the truth.",
        "land and freedom": "A young British communist joins the militia in the Spanish Civil War, witnessing firsthand the ideological conflicts that threaten to tear the Republican side apart.",
        "last action hero": "A magic movie ticket transports a young fan into the world of his favorite action hero, blurring the line between Hollywood fantasy and real-world danger.",
        "lawless": "Three bootlegging brothers in Prohibition-era Virginia build a thriving empire but must contend with a sadistic lawman sent to shut them down.",
        "legend 1985": "In a mythical forest realm, a young hero must stop the Lord of Darkness from plunging the world into eternal night by destroying the last unicorns.",
        "legend 2015": "The true story of identical twin gangsters Reggie and Ronnie Kray who terrorized London during the 1960s with their organized crime empire.",
        "logan": "In a bleak future, a weary Wolverine cares for an ailing Professor X while protecting a young mutant girl pursued by dark forces.",
        "looper": "In a future where time travel is used by the mob to dispose of targets, a hitman faces a moral crisis when his older self is sent back for elimination.",
        "lucy": "A woman accidentally absorbs a powerful synthetic drug that unlocks increasingly dangerous superhuman abilities, giving her access to 100% of her brain capacity.",
        "man on fire": "A burned-out ex-CIA operative becomes a bodyguard for a young girl in Mexico City, and when she's kidnapped, he unleashes a brutal campaign of vengeance.",
        "maverick": "A charming gambler on his way to a major poker tournament teams up with a con woman and a lawman for a comedic adventure across the Old West.",
        "men in black iii": "Agent J travels back in time to 1969 to stop an alien from assassinating his partner Agent K and altering the course of history.",
        "moon": "A solitary astronaut nearing the end of a three-year stint mining helium on the Moon makes a disturbing discovery that challenges everything he knows about himself.",
        "next of kin": "A Chicago cop from the hills of Kentucky pursues the mob killers who murdered his brother, torn between the law and his family's code of mountain justice.",
        "no country for old men": "A hunter stumbles upon a drug deal gone wrong and takes the cash, setting off a violent chain of events as a relentless killer tracks him across the Texas desert.",
        "no sudden move": "In 1950s Detroit, a group of small-time criminals are hired to steal what they think is a simple document, only to discover they're in way over their heads.",
        "oblivion": "A drone repairman stationed on a devastated Earth begins to question everything he knows when he rescues a stranger from a crashed spacecraft.",
        "oldboy": "A man imprisoned in a cell for 15 years without explanation is suddenly released and given five days to find his captor and uncover the reason for his torment.",
        "out of the furnace": "When a war veteran disappears into a criminal underworld, his older brother risks everything to bring him home and confront the violent men responsible.",
        "point break": "An FBI agent goes undercover to infiltrate a gang of surfers suspected of pulling off a string of bank robberies.",
        "prometheus": "A team of explorers discovers a clue to the origins of mankind on Earth, leading them on a journey to a distant moon that turns into a terrifying fight for survival.",
        "red dawn": "A group of teenagers becomes the last line of defense when a foreign military force invades their small American town.",
        "red heat": "A tough Soviet cop is paired with a wisecracking Chicago detective to track down a Georgian drug lord who has fled to the United States.",
        "red tails": "The Tuskegee Airmen, the first African American fighter pilots in World War II, battle racism at home while proving themselves as elite warriors in the skies over Europe.",
        "rendition": "When an Egyptian-born American is detained by the CIA and sent overseas for interrogation, his wife fights to uncover the truth and bring him home.",
        "safe house": "A young CIA agent guarding a safe house in South Africa must go on the run when the facility is attacked, with a dangerous rogue operative in tow.",
        "safety not guaranteed": "Three magazine employees investigate a classified ad seeking a companion for time travel and discover the man behind it might not be crazy after all.",
        "salvador allende": "A documentary chronicling the life and presidency of Chile's Salvador Allende, from his democratic election to his overthrow in the CIA-backed 1973 military coup.",
        "savages": "Two marijuana growers face off against a ruthless Mexican cartel that kidnaps their shared girlfriend to force them into a partnership.",
        "seal team six": "The story of the elite Navy SEAL unit tasked with the secret mission to find and eliminate Osama bin Laden in his Pakistani compound.",
        "secret window": "A troubled writer discovers he's being stalked by a mysterious stranger who accuses him of plagiarism, and the confrontation turns increasingly menacing.",
        "seeking a friend for the end of the world": "With an asteroid set to destroy Earth in three weeks, a lonely man and his adventurous neighbor hit the road to find his high school sweetheart.",
        "serenity 2019": "A fishing boat captain's quiet life is shattered when his ex-wife appears begging him to kill her abusive new husband, but nothing on this island is what it seems.",
        "seven psychopaths": "A struggling screenwriter gets inadvertently pulled into the criminal underworld when his friends kidnap the beloved dog of a volatile gangster.",
        "sherlock holmes game of shadows": "Sherlock Holmes and Dr. Watson match wits with their most cunning adversary yet, Professor Moriarty, in a deadly game that spans across Europe.",
        "sicario day of the soldado": "The U.S. government enlists the help of an operative and a hitman to provoke a war between rival Mexican drug cartels.",
        "skyfall": "When MI6 comes under attack, James Bond must track down and eliminate the threat while confronting ghosts from his own past.",
        "sleepy hollow": "A superstitious New York detective is sent to investigate a series of decapitations in a small village and encounters the terrifying Headless Horseman.",
        "snow white and the huntsman": "In a dark reimagining of the fairy tale, a huntsman ordered to capture an escaped princess instead becomes her protector in a quest to overthrow the evil queen.",
        "source code": "A soldier wakes up in another man's body on a commuter train and has eight minutes to find a bomb before it explodes, reliving the scenario again and again.",
        "star wars": "A young farm boy joins a ragtag group of rebels to rescue a princess and destroy the Empire's planet-killing superweapon.",
        "state of grace": "An undercover cop returns to his old Hell's Kitchen neighborhood to infiltrate the Irish mob run by his childhood best friends.",
        "sucker punch": "A young woman institutionalized by her abusive stepfather retreats into fantastical worlds of her imagination while plotting her escape with fellow patients.",
        "suicide kings": "A group of privileged young men kidnap a retired mob boss to raise ransom money for a friend's sister, but their plan quickly unravels.",
        "sully": "Captain Chesley Sullenberger must prove his heroic emergency landing on the Hudson River wasn't reckless when investigators question his judgment.",
        "sunshine": "A team of astronauts embarks on a desperate mission to reignite the dying Sun with a massive nuclear bomb, but the journey takes a terrifying turn.",
        "superbad": "Two inseparable high school friends navigate one wild night of parties and misadventures as they try to make the most of their last weeks before college.",
        "ted": "A man's childhood wish brings his teddy bear to life, but the now-crude, pot-smoking bear threatens to derail his adult relationships.",
        "tenet": "A secret agent armed with a single word must navigate a twilight world of international espionage and bend time itself to prevent World War III.",
        "thats my boy": "A man who fathered a son as a teenager tries to reconnect with his now-adult child right before his wedding, bringing chaos and embarrassment along.",
        "the book of eli": "A lone warrior walks across a post-apocalyptic America protecting a sacred book that holds the key to saving humanity.",
        "the accountant": "A math savant who works as a freelance accountant for dangerous criminal organizations is pursued by a Treasury agent while protecting a young woman who's discovered a financial discrepancy.",
        "the baytown outlaws": "Three redneck brothers are hired by a woman to rescue her godson from her abusive ex-husband, leading to a wild, bullet-riddled road trip.",
        "the bourne legacy": "When the CIA's black-ops programs are exposed, a genetically enhanced operative must go on the run to survive and secure the medication he needs to stay alive.",
        "the campaign": "Two rival Southern politicians engage in an increasingly absurd and dirty race for a congressional seat in North Carolina.",
        "the dictator": "A tyrannical dictator from a fictional North African country travels to New York and is stripped of his identity, forcing him to live among the people he oppresses.",
        "the dinosaur project": "A British expedition to the Congo discovers a hidden population of living dinosaurs and captures the terrifying encounter on film.",
        "the expendables 2": "A team of elite mercenaries embarks on a seemingly simple mission that turns into a fight for vengeance against a ruthless arms dealer.",
        "the hobbit an unexpected journey": "A reluctant hobbit is swept into an epic quest by a wizard and thirteen dwarves to reclaim their homeland from a fearsome dragon.",
        "the hunger games": "In a dystopian future, a teenage girl volunteers to take her sister's place in a televised death match where 24 young people fight until only one remains.",
        "the hunting party": "A disgraced war correspondent and his cameraman sneak into Bosnia to find the most wanted war criminal in the world, with unexpected results.",
        "the illusionist": "A mysterious magician in turn-of-the-century Vienna uses his extraordinary abilities to win back his childhood love from a powerful and corrupt crown prince.",
        "the inevitable defeat of mister and pete": "Two Brooklyn boys must fend for themselves through a sweltering New York summer after their mothers are taken by the authorities.",
        "the invasion": "A Washington D.C. psychiatrist discovers that an alien epidemic is transforming humans into emotionless beings and races to find a way to stop it before it's too late.",
        "the man with iron fists": "In feudal China, a blacksmith who makes weapons for warring clans is forced to unleash his own fighting skills to defend his village.",
        "the nice guys": "A mismatched pair of private eyes in 1970s Los Angeles stumble onto a sprawling criminal conspiracy while investigating the disappearance of a young woman.",
        "the numbers station": "A disgraced CIA operative is assigned to protect a code operator at a remote numbers station, and they must fight off an assault by unknown attackers.",
        "the raven": "When a serial killer begins recreating Edgar Allan Poe's gruesome tales, the author himself joins the hunt to stop the murders and save someone he loves.",
        "the road": "A father and his young son walk alone through a burned, post-apocalyptic America, pushing a shopping cart and clinging to survival and each other.",
        "the score": "An aging thief plans one last heist at the Montreal Customs House, but his volatile young partner threatens to bring the whole job crashing down.",
        "the siege": "After a series of terrorist bombings in New York City, the government declares martial law, and an FBI agent and a CIA operative race to stop the next attack.",
        "the tall man": "When children begin to vanish from a struggling mining town, a local nurse sets out to uncover the truth behind the legend of the Tall Man.",
        "the watch": "Four suburban dads form a neighborhood watch group to get away from their families, only to discover their town has been invaded by aliens.",
        "the african queen": "During World War I, a gin-swilling riverboat captain and a prim missionary team up for a dangerous journey down an African river to torpedo a German warship.",
        "the big short": "A handful of outsiders and misfits see the global financial collapse coming before anyone else and bet against the big banks in a daring gamble.",
        "the day the earth stood still": "An alien visitor and his powerful robot companion arrive on Earth with a dire warning: change your ways or face elimination.",
        "the gray man": "A CIA operative turned elite assassin is hunted across the globe by a psychopathic former colleague after accidentally uncovering dark agency secrets.",
        "the hitmans bodyguard": "A top protection agent is forced to guard his mortal enemy, a notorious hitman, while transporting him to testify at the International Court of Justice.",
        "the man from nowhere": "A quiet pawnshop owner with a mysterious past unleashes his deadly skills to save a young girl from drug traffickers who have kidnapped her.",
        "the man from uncle": "A CIA agent and a KGB operative are forced to set aside their rivalry and work together to stop a shadowy criminal organization from building a nuclear weapon.",
        "the maze runner": "A teenager wakes up in a massive maze with no memory of his past and must work with other trapped boys to find a way out.",
        "the mule": "A 90-year-old horticulturist becomes a drug courier for a Mexican cartel, attracting the attention of the DEA agent on his trail.",
        "the place beyond the pines": "A motorcycle stunt rider turns to bank robbery to support his newborn son, setting off a chain of events that will affect multiple families for decades.",
        "the prestige": "Two rival magicians in Victorian London engage in a bitter and escalating battle to create the ultimate illusion, each obsessed with outdoing the other.",
        "the sisters brothers": "Two brothers working as hired assassins in 1850s Oregon are sent to kill a prospector, but the journey forces them to reconsider their violent way of life.",
        "the texas killing fields": "Two detectives in a small Texas city investigate a series of unsolved murders of young women found in the surrounding oil fields.",
        "this is 40": "A married couple with two kids confronts the realities of work, family, aging, and each other as they both approach their 40th birthdays.",
        "tomcats": "A group of bachelor friends place a bet on who will be the last to get married, and the final two go to outrageous lengths to win the pot.",
        "top gun maverick": "After decades as a top aviator, Pete 'Maverick' Mitchell is called back to train a new generation of fighter pilots for an impossible mission.",
        "total recall 2012": "A factory worker begins to suspect his entire life is a false memory when a visit to a company that implants artificial memories goes horribly wrong.",
        "towelhead": "A thirteen-year-old Arab American girl navigates racism, sexual awakening, and abuse after being sent to live with her strict father in suburban Texas.",
        "transcendence": "A dying AI researcher uploads his consciousness into a supercomputer, but his growing power raises questions about where technology ends and humanity begins.",
        "the bourne ultimatum": "Jason Bourne races across the globe to uncover the full truth about his identity and the CIA black-ops program that created him, while staying one step ahead of his hunters.",
        "v for vendetta": "In a totalitarian future Britain, a masked vigilante known as V inspires a young woman and the public to rise up against their oppressive government.",
        "valkyrie": "A group of German officers plots to assassinate Adolf Hitler and seize control of the government using the regime's own emergency plan.",
        "war": "An FBI agent seeks revenge on a mysterious assassin who killed his partner, but their deadly cat-and-mouse game hides a shocking truth.",
        "war for the planet of the apes": "Caesar and his apes are forced into a devastating conflict with a ruthless human army led by a colonel who will stop at nothing to wipe them out.",
        "zero dark thirty": "A CIA analyst spends a decade tracking down leads that ultimately take her to Osama bin Laden's compound in Pakistan.",
        "zulu": "A small garrison of British soldiers must defend their outpost against thousands of Zulu warriors at the Battle of Rorke's Drift in 1879.",
        "ice age": "A woolly mammoth, a saber-toothed tiger, and a wisecracking sloth band together to return a human baby to its tribe during the Ice Age.",

        // TV Shows
        "blue lights": "Rookie police officers in Belfast navigate the dangers and moral complexities of policing one of the UK's most challenging cities.",
        "for all mankind": "An alternate history where the Soviet Union beats the U.S. to the Moon, igniting a decades-long space race that transforms the world.",
        "slow horses": "A team of disgraced MI5 agents banished to a dead-end department stumble into real conspiracies while working under their slovenly, brilliant boss.",
        "raised by wolves": "Two androids are tasked with raising human children on a mysterious virgin planet, but the burgeoning colony is threatened by religious differences and the planet's strange secrets.",
        "human weapon": "Two martial arts enthusiasts travel the globe to learn and test themselves in the world's most dangerous fighting styles.",
    ]

    static func lookup(_ title: String) -> String? {
        let key = title.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        if let exact = descriptions[key] { return exact }
        for (k, v) in descriptions {
            if key.contains(k) || k.contains(key) { return v }
        }
        return nil
    }

    // MARK: - Genres

    static let genres: [String: String] = [
        // Movies
        "gravity": "Sci-Fi",
        "midnight express": "Drama",
        "12 strong": "War",
        "1917": "War",
        "a haunted house": "Comedy",
        "a knights tale": "Adventure",
        "a man called otto": "Drama",
        "abraham lincoln vampire hunter": "Action",
        "act of valor": "Action",
        "all the pretty horses": "Western",
        "all the money in the world": "Thriller",
        "american hustle": "Crime",
        "american reunion": "Comedy",
        "apocalypto": "Action",
        "appaloosa": "Western",
        "arctic": "Drama",
        "argo": "Thriller",
        "avengers": "Action",
        "baby makers": "Comedy",
        "bashir": "Documentary",
        "battleship": "Action",
        "bernie": "Crime",
        "blade runner 2049": "Sci-Fi",
        "body of lies": "Thriller",
        "bridge of spies": "Drama",
        "broken city": "Thriller",
        "bullitt": "Action",
        "cartel land": "Documentary",
        "casino royale": "Action",
        "catch a fire": "Drama",
        "cheech and chong up in smoke": "Comedy",
        "children of men": "Sci-Fi",
        "cloverfield": "Sci-Fi",
        "cocaine cowboys": "Documentary",
        "collateral": "Thriller",
        "contraband": "Action",
        "cool hand luke": "Drama",
        "cowboys and aliens": "Sci-Fi",
        "cry macho": "Drama",
        "cut bank": "Thriller",
        "dallas buyers club": "Drama",
        "dark knight rises": "Action",
        "dark shadows": "Comedy",
        "darkest hour": "Drama",
        "deadpool": "Action",
        "death proof": "Thriller",
        "dien bien phu": "War",
        "district 9": "Sci-Fi",
        "django unchained": "Western",
        "dredd": "Action",
        "dune": "Sci-Fi",
        "edge of tomorrow": "Sci-Fi",
        "elysium": "Sci-Fi",
        "empire of the sun": "War",
        "end of watch": "Crime",
        "equilibrium": "Sci-Fi",
        "fantastic fungi": "Documentary",
        "felon": "Drama",
        "fifth element": "Sci-Fi",
        "finch": "Sci-Fi",
        "flight": "Drama",
        "ford v ferrari": "Drama",
        "free state of jones": "War",
        "fury": "War",
        "get the gringo": "Action",
        "glengarry glen ross": "Drama",
        "gran torino": "Drama",
        "haven": "Thriller",
        "here comes the boom": "Comedy",
        "hero": "Action",
        "home": "Animation",
        "hotel mumbai": "Thriller",
        "house at the end of the street": "Horror",
        "hyena road": "War",
        "i am legend": "Sci-Fi",
        "immortals": "Action",
        "in the valley of elah": "Drama",
        "incredible burt wonderstone": "Comedy",
        "inglourious basterds": "War",
        "jack reacher": "Action",
        "jack reacher never go back": "Action",
        "jimi hendrix": "Drama",
        "joe's palace": "Drama",
        "john carter": "Sci-Fi",
        "john dies at the end": "Horror",
        "john wick": "Action",
        "john wick chapter 2": "Action",
        "journey 2": "Adventure",
        "jurassic world": "Sci-Fi",
        "kill bill vol 1": "Action",
        "killer joe": "Crime",
        "killers of the flower moon": "Crime",
        "killing them softly": "Crime",
        "kiss of the damned": "Horror",
        "knives out": "Crime",
        "land and freedom": "War",
        "last action hero": "Action",
        "lawless": "Crime",
        "legend 1985": "Adventure",
        "legend 2015": "Crime",
        "logan": "Action",
        "looper": "Sci-Fi",
        "lucy": "Action",
        "man on fire": "Action",
        "maverick": "Comedy",
        "men in black iii": "Sci-Fi",
        "moon": "Sci-Fi",
        "next of kin": "Action",
        "no country for old men": "Thriller",
        "no sudden move": "Crime",
        "oblivion": "Sci-Fi",
        "oldboy": "Thriller",
        "out of the furnace": "Drama",
        "point break": "Action",
        "prometheus": "Sci-Fi",
        "red dawn": "Action",
        "red heat": "Action",
        "red tails": "War",
        "rendition": "Thriller",
        "safe house": "Action",
        "safety not guaranteed": "Comedy",
        "salvador allende": "Documentary",
        "savages": "Thriller",
        "seal team six": "Action",
        "secret window": "Thriller",
        "seeking a friend for the end of the world": "Comedy",
        "serenity 2019": "Thriller",
        "seven psychopaths": "Comedy",
        "sherlock holmes game of shadows": "Action",
        "sicario day of the soldado": "Action",
        "skyfall": "Action",
        "sleepy hollow": "Horror",
        "snow white and the huntsman": "Adventure",
        "source code": "Sci-Fi",
        "star wars": "Sci-Fi",
        "state of grace": "Crime",
        "sucker punch": "Action",
        "suicide kings": "Thriller",
        "sully": "Drama",
        "sunshine": "Sci-Fi",
        "superbad": "Comedy",
        "ted": "Comedy",
        "tenet": "Sci-Fi",
        "thats my boy": "Comedy",
        "the book of eli": "Action",
        "the accountant": "Action",
        "the baytown outlaws": "Action",
        "the bourne legacy": "Action",
        "the campaign": "Comedy",
        "the dictator": "Comedy",
        "the dinosaur project": "Adventure",
        "the expendables 2": "Action",
        "the hobbit an unexpected journey": "Adventure",
        "the hunger games": "Sci-Fi",
        "the hunting party": "Thriller",
        "the illusionist": "Drama",
        "the inevitable defeat of mister and pete": "Drama",
        "the invasion": "Sci-Fi",
        "the man with iron fists": "Action",
        "the nice guys": "Comedy",
        "the numbers station": "Thriller",
        "the raven": "Thriller",
        "the road": "Drama",
        "the score": "Crime",
        "the siege": "Thriller",
        "the tall man": "Thriller",
        "the watch": "Comedy",
        "the african queen": "Adventure",
        "the big short": "Drama",
        "the day the earth stood still": "Sci-Fi",
        "the gray man": "Action",
        "the hitmans bodyguard": "Action",
        "the man from nowhere": "Action",
        "the man from uncle": "Action",
        "the maze runner": "Sci-Fi",
        "the mule": "Crime",
        "the place beyond the pines": "Crime",
        "the prestige": "Thriller",
        "the sisters brothers": "Western",
        "the texas killing fields": "Crime",
        "this is 40": "Comedy",
        "tomcats": "Comedy",
        "top gun maverick": "Action",
        "total recall 2012": "Sci-Fi",
        "towelhead": "Drama",
        "transcendence": "Sci-Fi",
        "the bourne ultimatum": "Action",
        "v for vendetta": "Sci-Fi",
        "valkyrie": "Thriller",
        "war": "Action",
        "war for the planet of the apes": "Sci-Fi",
        "zero dark thirty": "Thriller",
        "zulu": "War",
        "ice age": "Animation",

        // TV Shows
        "blue lights": "Drama",
        "for all mankind": "Sci-Fi",
        "slow horses": "Thriller",
        "raised by wolves": "Sci-Fi",
        "human weapon": "Documentary",
    ]

    // MARK: - Rotten Tomatoes Ratings

    static let ratings: [String: Int] = [
        "gravity": 96,
        "midnight express": 93,
        "12 strong": 54,
        "1917": 89,
        "a haunted house": 10,
        "a knights tale": 58,
        "a man called otto": 70,
        "abraham lincoln vampire hunter": 34,
        "act of valor": 24,
        "all the pretty horses": 33,
        "all the money in the world": 87,
        "american hustle": 92,
        "american reunion": 45,
        "apocalypto": 65,
        "appaloosa": 75,
        "arctic": 91,
        "argo": 96,
        "avengers": 91,
        "baby makers": 0,
        "bashir": 97,
        "battleship": 34,
        "bernie": 92,
        "blade runner 2049": 88,
        "body of lies": 53,
        "bridge of spies": 91,
        "broken city": 29,
        "bullitt": 97,
        "cartel land": 89,
        "casino royale": 95,
        "catch a fire": 63,
        "cheech and chong up in smoke": 68,
        "children of men": 92,
        "cloverfield": 77,
        "cocaine cowboys": 77,
        "collateral": 86,
        "contraband": 44,
        "cool hand luke": 97,
        "cowboys and aliens": 44,
        "cry macho": 33,
        "cut bank": 42,
        "dallas buyers club": 93,
        "dark knight rises": 87,
        "dark shadows": 36,
        "darkest hour": 85,
        "deadpool": 85,
        "death proof": 65,
        "district 9": 90,
        "django unchained": 87,
        "dredd": 79,
        "dune": 83,
        "edge of tomorrow": 91,
        "elysium": 66,
        "empire of the sun": 72,
        "end of watch": 85,
        "equilibrium": 40,
        "fantastic fungi": 100,
        "felon": 53,
        "fifth element": 71,
        "finch": 69,
        "flight": 78,
        "ford v ferrari": 92,
        "free state of jones": 44,
        "fury": 76,
        "get the gringo": 62,
        "glengarry glen ross": 80,
        "gran torino": 80,
        "here comes the boom": 41,
        "hero": 95,
        "home": 45,
        "hotel mumbai": 75,
        "house at the end of the street": 11,
        "hyena road": 60,
        "i am legend": 68,
        "immortals": 36,
        "in the valley of elah": 72,
        "incredible burt wonderstone": 36,
        "inglourious basterds": 89,
        "jack reacher": 62,
        "jack reacher never go back": 38,
        "john carter": 52,
        "john dies at the end": 61,
        "john wick": 86,
        "john wick chapter 2": 89,
        "journey 2": 43,
        "jurassic world": 71,
        "kill bill vol 1": 85,
        "killer joe": 79,
        "killers of the flower moon": 93,
        "killing them softly": 74,
        "kiss of the damned": 52,
        "knives out": 97,
        "land and freedom": 89,
        "last action hero": 38,
        "lawless": 66,
        "legend 1985": 50,
        "legend 2015": 60,
        "logan": 94,
        "looper": 93,
        "lucy": 67,
        "man on fire": 39,
        "maverick": 64,
        "men in black iii": 69,
        "moon": 90,
        "no country for old men": 93,
        "no sudden move": 90,
        "oblivion": 53,
        "oldboy": 81,
        "out of the furnace": 54,
        "point break": 69,
        "prometheus": 73,
        "red dawn": 12,
        "red heat": 45,
        "red tails": 40,
        "rendition": 47,
        "safe house": 53,
        "safety not guaranteed": 91,
        "savages": 52,
        "secret window": 46,
        "seeking a friend for the end of the world": 55,
        "serenity 2019": 21,
        "seven psychopaths": 83,
        "sherlock holmes game of shadows": 59,
        "sicario day of the soldado": 62,
        "skyfall": 92,
        "sleepy hollow": 68,
        "snow white and the huntsman": 49,
        "source code": 92,
        "star wars": 93,
        "state of grace": 96,
        "sucker punch": 22,
        "suicide kings": 47,
        "sully": 85,
        "sunshine": 76,
        "superbad": 88,
        "ted": 69,
        "tenet": 69,
        "thats my boy": 20,
        "the book of eli": 47,
        "the accountant": 52,
        "the baytown outlaws": 38,
        "the bourne legacy": 56,
        "the campaign": 67,
        "the dictator": 58,
        "the expendables 2": 67,
        "the hobbit an unexpected journey": 64,
        "the hunger games": 84,
        "the illusionist": 74,
        "the inevitable defeat of mister and pete": 68,
        "the invasion": 19,
        "the man with iron fists": 51,
        "the nice guys": 92,
        "the numbers station": 15,
        "the raven": 22,
        "the road": 74,
        "the score": 72,
        "the siege": 59,
        "the tall man": 58,
        "the watch": 17,
        "the african queen": 97,
        "the big short": 88,
        "the day the earth stood still": 21,
        "the gray man": 46,
        "the hitmans bodyguard": 43,
        "the man from nowhere": 100,
        "the man from uncle": 68,
        "the maze runner": 65,
        "the mule": 68,
        "the place beyond the pines": 80,
        "the prestige": 76,
        "the sisters brothers": 87,
        "the texas killing fields": 41,
        "this is 40": 51,
        "tomcats": 5,
        "top gun maverick": 96,
        "total recall 2012": 30,
        "towelhead": 47,
        "transcendence": 19,
        "the bourne ultimatum": 92,
        "v for vendetta": 73,
        "valkyrie": 63,
        "war": 14,
        "war for the planet of the apes": 93,
        "zero dark thirty": 91,
        "zulu": 89,
        "ice age": 77,

        // TV Shows
        "blue lights": 100,
        "for all mankind": 85,
        "slow horses": 96,
        "raised by wolves": 77,
    ]

    static func genreLookup(_ title: String) -> String? {
        let key = title.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        if let exact = genres[key] { return exact }
        for (k, v) in genres {
            if key.contains(k) || k.contains(key) { return v }
        }
        return nil
    }

    static func ratingLookup(_ title: String) -> Int? {
        let key = title.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        if let exact = ratings[key] { return exact }
        for (k, v) in ratings {
            if key.contains(k) || k.contains(key) { return v }
        }
        return nil
    }
}
